import { DefaultTheme } from 'styled-components';

export const darkTheme: DefaultTheme = {
  colors: {
    background: '#121212',
    backgroundSecondary: '#1E1E1E',
    foreground: '#FFFFFF',
    primary: '#550AB1',
    primaryForeground: '#FFFFFF',
    secondary: '#1A1A1A',
    secondaryForeground: '#FFFFFF',
    muted: '#2A2A2A',
    mutedForeground: '#AAAAAA',
    accent: '#3D2C8D',
    accentForeground: '#FFFFFF',
    destructive: '#FF4D4F',
    destructiveForeground: '#FFFFFF',
    border: '#2D2D2D',
    input: '#1A1A1A',
    ring: '#550AB1',
    card: '#1A1A1A',
    cardForeground: '#FFFFFF',
    popover: '#1A1A1A',
    popoverForeground: '#FFFFFF',
    sidebar: '#1E1E1E',
    sidebarForeground: '#FFFFFF',
    sidebarPrimary: '#550AB1',
    sidebarPrimaryForeground: '#FFFFFF',
    sidebarAccent: '#3D2C8D',
    sidebarAccentForeground: '#FFFFFF',
    sidebarBorder: '#2D2D2D',
    sidebarRing: '#550AB1',
  },
  space: {
    default: 16,
  },
  radii: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
};
