import { DefaultTheme } from 'styled-components';

export const lightTheme: DefaultTheme = {
  colors: {
    background: '#FFFFFF',
    backgroundSecondary: '#EEEEEE',
    foreground: '#121212',
    primary: '#1D013F',
    primaryForeground: '#FFFFFF',
    secondary: '#F2F2F2',
    secondaryForeground: '#121212',
    muted: '#F5F5F5',
    mutedForeground: '#555555',
    accent: '#E0E0FF',
    accentForeground: '#1D013F',
    destructive: '#FF4D4F',
    destructiveForeground: '#FFFFFF',
    border: '#DDDDDD',
    input: '#F5F5F5',
    ring: '#1D013F',
    card: '#FFFFFF',
    cardForeground: '#121212',
    popover: '#FFFFFF',
    popoverForeground: '#121212',
    sidebar: '#FAFAFA',
    sidebarForeground: '#121212',
    sidebarPrimary: '#1D013F',
    sidebarPrimaryForeground: '#FFFFFF',
    sidebarAccent: '#E0E0FF',
    sidebarAccentForeground: '#1D013F',
    sidebarBorder: '#DDDDDD',
    sidebarRing: '#1D013F',
  },
  space: {
    default: 16,
  },
  radii: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
};
